### ISSUE TITLE
HBTwitterCell Issues

### ISSUE THREAD

**Issue by iCrazeiOS** [hbang/libcephei#38]
For the past few weeks, all HBTwitterCells have had a grey/blank icon, rather than the user's profile picture.

Also, when I tap on the cell, it sometimes tells me to login to twitter, even though I already am...

Are either of these known issues? Thanks.

**Comment by Greigh** [comment]
I have the same issue. I was just about to submit the issue for a tweak I just made😂

**Comment by kirb** [comment]
This is because avatars.io shut down without notice a month or two ago. Previously we were using an undocumented feature of twitter.com that was working on and off starting from around December. This is because they didn’t implement the feature in the new twitter.com site, which they were A/B testing for logged-out users at the time. Logged-in users always got the new site, but logged-out had a small chance you’d get the new site. Since then, they increased it to 100% of users except those on old browsers. The old site is to be discontinued… wow, actually tomorrow, June 1st.

Apparently the owners of avatars.io decided it was ok to shut down without any notice whatsoever, and at the same time, also continue renewing the domain (it was to expire a week ago, and now it’s been renewed till 2021). It’s free and all, I know, but it’s been around for a decade, became pretty widely used, and then just disappeared with almost no notice. Amusingly, the ex-CEO of the company that built avatars.io [predicted it](https://twitter.com/gregarious/status/1207376009122779136) back in December when I was desperately looking for another solution.

The problem now is that it’s hard to trust any 3rd-party service to stay up. I know there are a few out there, but what happens when they decide it costs too much and it disappears overnight. Nobody can win here, it’s stupid, and it’s all because Twitter doesn’t think we should even be allowed to have a convenient API to get profile photos to embed in our apps - unless we get the user to authorise our app to use the Twitter API through their account, which is just silly. Sadly, it’s [just how the world is now](https://www.youtube.com/watch?v=BxV14h0kFs0).

What I’ve done about it for Cephei 1.15.1 which I’ll release shortly:

* I figured out the profile_image URLs still work on mobile.twitter.com if you give it a super old user agent, *for now*. Implemented in f2d341d.
* Since who knows how long that will last, I also added an `avatarURL` property. You could set it to your GitHub avatar for instance, e.g., [`https://github.com/kirb.png`](https://github.com/kirb.png). Implemented in 368cfe6.

About your other issue, we don’t control what happens after you tap, it’s probably Twitter A/B testing whether they should show a login interstitial or not.

**Comment by iCrazeiOS** [comment]
Thanks for the reply, will look forward for the update!

On 30 May 2020, at 14:19, Adam Demasi <notifications@github.com> wrote:

﻿

This is because avatars.io shut down without notice a month or two ago. Previously we were using an undocumented feature of twitter.com that was working on and off starting from around December. This is because they didn’t implement the feature in the new twitter.com site, which they were A/B testing for logged-out users at the time. Logged-in users always got the new site, but logged-out had a small chance you’d get the new site. Since then, they increased it to 100% of users except those on old browsers. The old site is to be discontinued… wow, actually tomorrow, June 1st.

Apparently the owners of avatars.io decided it was ok to shut down without any notice whatsoever, and at the same time, also continue renewing the domain (it was to expire a week ago, and now it’s been renewed till 2021). It’s free and all, I know, but it’s been around for a decade, became pretty widely used, and then just disappeared with almost no notice. Amusingly, the ex-CEO of the company that built avatars.io predicted it<https://twitter.com/gregarious/status/1207376009122779136> back in December when I was desperately looking for another solution.

The problem now is that it’s hard to trust any 3rd-party service to stay up. I know there are a few out there, but what happens when they decide it costs too much and it disappears overnight. Nobody can win here, it’s stupid, and it’s all because Twitter doesn’t think we should even be allowed to have a convenient API to get profile photos to embed in our apps - unless we get the user to authorise our app to use the Twitter API through their account, which is just silly. Sadly, it’s just how the world is now<https://www.youtube.com/watch?v=BxV14h0kFs0>.

What I’ve done about it for Cephei 1.15.1 which I’ll release shortly:

  *   I figured out the profile_image URLs still work on mobile.twitter.com if you give it a super old user agent, for now. Implemented in f2d341d<https://github.com/hbang/libcephei/commit/f2d341d1d1d79a9f51db009869258bc13f68fd55>.
  *   Since who knows how long that will last, I also added an avatarURL property. You could set it to your GitHub avatar for instance, e.g., https://github.com/kirb.png. Implemented in 368cfe6<https://github.com/hbang/libcephei/commit/368cfe6e11027a7ce417d81eccb367a585ec1497>.

About your other issue, we don’t control what happens after you tap, it’s probably Twitter A/B testing whether they should show a login interstitial or not.
